version: "3"

services:
  api:
    build: .
    image: api-command:latest
    ports:
      - "4000:3000"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  mongodb-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
