//// This file is only a examle file, to build up your commands to send

// template
let theCommand = {
	id: "a unique ID(uuid)", //This id marks the command as unique
	datetime: "unixTimestamp", //The unixtimestampt on send the command
	command: "thCommand", //The command for the API
	params: { param1: 1, param2: "2" }, //A optional paramerterlist
	data: { any: "any" }, //a optional datablock to the API
	message: "message", //A optional message for the LOG

	reponse: {
		// This reponse is generated by the API
		datetime: "unixTimestamp", //The datetime from the API response
		data: { any: "any" }, //A optional response datablock from the API
	},
};
